###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/fastlane/fastlane/blob/master/deliver/Deliverfile.md

app_identifier "com.osedea.opensource.instameow" # The bundle identifier of your app
username ENV['APPLE_ID']
